server:
  port: 8004   
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rentvehicledb
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 800000
  ReadTimeout: 800000
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false